#!/bin/bash

if [ "$1" == "create" ]
then
  aptly mirror create -architectures=amd64,i386 -filter='Priority (required) | Priority (important) | Priority (standard) | kde-base | emacs | iceweasel' -filter-with-deps jessie-updates http://ftp.us.debian.org/debian/ jessie-updates main

  aptly mirror create -architectures=amd64,i386 -filter='Priority (required) | Priority (important) | Priority (standard) | kde-base | emacs | iceweasel' -filter-with-deps jessie-security http://security.debian.org/ jessie/updates main

  aptly mirror create -architectures=amd64,i386 -filter='Priority (required) | Priority (important) | Priority (standard) | kde-base | emacs | iceweasel' -filter-with-deps jessie-main http://ftp.us.debian.org/debian/ jessie main

  aptly mirror create steam http://repo.steampowered.com/steam/ precise steam
else
  timestamp=`date "+%Y%m%d%H%M"`

  aptly mirror update jessie-main
  aptly mirror update jessie-security
  aptly mirror update jessie-updates
  aptly mirror update steam
  
  aptly snapshot create jessie-main-$timestamp from mirror jessie-main
  aptly snapshot create jessie-updates-$timestamp from mirror jessie-updates
  aptly snapshot create jessie-security-$timestamp from mirror jessie-security
  aptly snapshot create steam-$timestamp from mirror steam

  aptly snapshot merge -latest jessie-final-$timestamp jessie-main-$timestamp jessie-updates-$timestamp jessie-security-$timestamp steam-$timestamp

  aptly publish switch jessie jessie-final-$timestamp

  aptly db cleanup
fi
