#!/bin/bash

timestamp=`date "+%Y%m%d%H%M"`

aptly mirror update jessie-main
aptly mirror update jessie-security
aptly mirror update jessie-updates
  
aptly snapshot create jessie-main-$timestamp from mirror jessie-main
aptly snapshot create jessie-updates-$timestamp from mirror jessie-updates
aptly snapshot create jessie-security-$timestamp from mirror jessie-security

aptly snapshot merge -latest jessie-final-$timestamp jessie-main-$timestamp jessie-updates-$timestamp jessie-security-$timestamp

aptly publish switch jessie jessie-final-$timestamp

aptly db cleanup
